[facility]
name = "Advanced Photon Source"

[beamline]
name = "25-ID-C"
is_connected = true

[xray_source]

type = "undulator"
prefix = "ID25ds:"

[database.databroker]

catalog = "s25idc"

[queueserver]
kafka_topic = "s25idc_queueserver"
control_host = "164.54.135.25"
control_port = "60615"
info_host = "fedorov"
info_port = "60625"

[shutter]

[shutter.A]

open_pv = "PSS:25ID:FES_OPEN_EPICS.VAL"
close_pv = "PSS:25ID:FES_CLOSE_EPICS.VAL"
status_pv = "PSS:25ID:A_BEAM_PRESENT"

[shutter.C]

open_pv = "PSS:25ID:SCS_OPEN_EPICS.VAL"
close_pv = "PSS:25ID:SCS_CLOSE_EPICS.VAL"
status_pv = "PSS:25ID:C_BEAM_PRESENT"

[ion_chamber.scaler]
ioc = "25idcVME"
record = "3820:scaler1"
channels = [2, 3, 4, 5, 6, 7, 8]

[ion_chamber.preamp]
ioc = "25idc"

[slits.KB_slits]

prefix = "25idcVME:KB"

[motor.VME_crate]
prefix = "25idcVME"
num_motors = 56

[motor.ORM1]
prefix = "25ida:ORM1"
num_motors = 4

[motor.ORM2]
prefix = "25ida:ORM2"
num_motors = 5

[motor.WB_slit]
prefix = "25ida:slits"
num_motors = 8

[motor.BPM]
prefix = "25ida:BPM"
num_motors = 1

[stage.Aerotech]
prefix = "25idc"
pv_vert = ":m2"
pv_horiz = ":m1"

[monochromator]
ioc = "25idbUP"
ioc_branch = "UP"

[undulator]
ioc = "ID25ds"

[fluorescence_detector.vortex_me4]
prefix = "20xmap4b"
electronics = "dxp"  # or "xspress3"
num_elements = 4

[camera]
imagej_command = "/home/beams/S25IDCUSER/ImageJ/ImageJ"

[camera.camBPM]
name = "Hutch A BPM"
description = "Hutch A BPM"
ioc = "25idaBPM"

[camera.camA]
name = "s25id-gige-A"
description = "GigE Vision A"
ioc = "25idgigeA"

[camera.camB]
name = "s25id-gige-B"
description = "GigE Vision B"
ioc = "25idgigeB"

[camera.camC]
name = "s25id-gige-C"
description = "GigE Vision C"
ioc = "25idgigeC"

[camera.camD]
name = "s25id-gige-D"
description = "GigE Vision D"
ioc = "25idgigeD"

[camera.camE]
name = "s25id-gige-E"
description = "GigE Vision E"
ioc = "25idgigeE"

[power_supply.NHQ01]

prefix = "25idc:NHQ01"
n_channels = 2

[area_detector.sim_det]

prefix = "25idSimDet"
device_class = "SimDetector"

[area_detector.cyclops]

prefix = "25idLambda250K"
device_class = "Lambda250K"
